services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: v79marketing-app
    ports:
      - "3070:80"
    environment:
      - NODE_ENV=production
      - PORT=3070
    restart: always

networks:
  default:
    name: v79_network
